---
version: '3'

volumes:
  deconz-data: {}

services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - deconz-data:/opt/deCONZ
    devices:
      - /dev/ttyAMA0
    ports:
      - 8787:80
      - 443:443
    environment:
      - TZ=Australia/Melbourne
      - DECONZ_DEVICE=/dev/ttyAMA0
      - DEBUG_INFO=1
