---
version: '3'

volumes:
  deconz-data: {}

services:
  deconz:
    image: marthoc/deconz:2.12.06
    container_name: deconz
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - deconz-data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyAMA0
    #ports:
    #  - 80:80
    #  - 443:443
    environment:
      - TZ=Australia/Melbourne
      - DECONZ_DEVICE=/dev/ttyAMA0
      - DEBUG_INFO=1
    #- DECONZ_WEB_PORT=80
    #- DECONZ_WS_PORT=443
